openapi: "3.0.2"
info:
  title: GOLANG SIMPLE CRUD
  description: API spec for simple restful API golang
  version: "1.0"
servers:
  - url: https://localhost:3000/api
paths:
  /categories:
    get:
      security:
        - CategoryAuth: []
      tags:
        - "Category API"
      summary: List all categories
      responses:
        "200":
          description: Success get All categories
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Category"
    post:
      security:
        - CategoryAuth: []
      tags:
        - "Category API"
      summary: create new category
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOrUpdateCategory"
      responses:
        "200":
          description: Success create category
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    $ref: "#/components/schemas/Category"
  /categories/{categoryId}:
    get:
      security:
        - CategoryAuth: []
      tags:
        - "Category API"
      summary: "get category by id"
      parameters:
        - name: categoryId
          in: path
          description: category id
          required: true
          schema:
            type: integer

      responses:
        "200":
          description: Success get category by id
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    $ref: "#/components/schemas/Category"
    put:
      security:
        - CategoryAuth: []
      tags:
        - "Category API"
      summary: "update category by id"
      parameters:
        - name: categoryId
          in: path
          description: category id
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOrUpdateCategory"
      responses:
        "200":
          description: Success update category by id
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    $ref: "#/components/schemas/Category"
    delete:
      security:
        - CategoryAuth: []
      tags:
        - "Category API"
      summary: "delete category by id"
      parameters:
        - name: categoryId
          in: path
          description: category id
          required: true
          schema:
            type: integer

      responses:
        "200":
          description: Success delete category by id
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string

components:
  securitySchemes:
    CategoryAuth:
      type: apiKey
      in: header
      name: X-API-KEY
      description: Authenctication for category api
  schemas:
    CreateOrUpdateCategory:
      type: object
      properties:
        name:
          type: string
    Category:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
